# Generated by Django 4.1.3 on 2022-12-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_img', models.ImageField(upload_to='pics')),
                ('t_name', models.CharField(max_length=250)),
                ('t_desc', models.TextField()),
            ],
        ),
    ]
